- hosts: localhost
  connection: local
  tasks:
    - import_tasks: file.yml
      tags:
        - file
    - import_tasks: asdf.yml
      tags:
        - asdf
    - import_tasks: apt.yml
      tags:
        - apt
    - import_tasks: fish.yml
      tags:
        - fish
    - import_tasks: go.yml
      tags:
        - go